# To create an environment from this file using conda, run:
# conda env create -f environment.yml

name: mps
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.16
  - flask=3.0.3
  - requests=2.32.3
  - flask-migrate=4.0.7
  - flask-sqlalchemy=3.1.1
  - bcrypt=4.2.1
  - python-dotenv
  - psycopg2-binary=2.9.10
  - flask-session=0.8.0
  - redis-py=5.2.1

